### ISSUE TITLE
Update snarkyjs version to 0.7.x

### ISSUE THREAD

**Issue by rpanic** [Comdex/snarky-smt#19]
When installing, it throws an error with the newest snarkyjs version that the dependency versions are not compatible.

To update, the snarkyjs version has to be upgraded and removed features replaced by their newer counterpart

**Comment by Comdex** [comment]
A version compatible with the latest snarkyjs is under development, and all APIs will better support Struct, which will bring breaking changes to existing APIs. The current progress depends on the fix of Struct related issues in snarkyjs: o1-labs/snarkyjs#567
